'use strict';
const {courses,slots}=BIO_DATA;const core=BIO_CORE;const KEY='bioschedule:2026-2:v1';let storageOK=true;let state;
try{state=core.normalize(JSON.parse(localStorage.getItem(KEY)),courses);}catch{state=core.normalize(null,courses);storageOK=false;}
const $=id=>document.getElementById(id);const esc=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const days=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
const fmt=n=>{const minutes=Math.round(n);return `${Math.floor(minutes/60)}h${minutes%60?' '+String(minutes%60).padStart(2,'0')+'min':''}`;};
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}}
function updateSave(){$('save-state').textContent=storageOK?'Salvo neste navegador':'Não foi possível salvar neste navegador';}
function catalog(){const opened=new Set([...document.querySelectorAll('.period[open]')].map(el=>el.dataset.period));const first=!$('courses').children.length;const focus=document.activeElement?.dataset.focus;
$('catalog-count').textContent=`${courses.length} no catálogo`;
$('courses').innerHTML=[...new Set(courses.map(c=>c.period))].map(period=>{const list=courses.filter(c=>c.period===period);return `<details class="period" data-period="${period}" ${opened.has(String(period))||(first&&period===1)?'open':''}><summary>${period==='9–10'?'9º e 10º períodos':period+'º período'}<span class="period-count">${list.length} matérias</span></summary>${list.map(c=>{const selected=!!state.selected[c.id],done=state.completed.includes(c.id);return `<article class="course ${selected?'selected':''} ${done?'done':''}"><label class="course-title"><input type="checkbox" data-action="select" data-id="${c.id}" data-focus="check-${c.id}" ${selected?'checked':''} ${done||!c.offered?'disabled':''}><span>${esc(c.name)}</span></label><p class="course-meta">${esc(c.short)} · ${c.sections.length?fmt((c.sections.find(s=>s.id===state.selected[c.id])||c.sections[0]).meetings.reduce((n,m)=>n+core.duration(m)/(m.frequency||1),0))+' / semana · ':''}${c.hours===null?'CH não informada':c.hours+'h'}${!c.offered?' · Não ofertada':''}</p><div class="course-actions">${c.sections.length?`<select data-action="section" data-id="${c.id}" data-focus="section-${c.id}" aria-label="Turma de ${esc(c.name)}" ${done?'disabled':''}>${c.sections.map(s=>`<option value="${esc(s.id)}" ${state.selected[c.id]===s.id?'selected':''}>Turma ${esc(s.id)}</option>`).join('')}</select>`:'<span class="course-meta">Sem horário fixo</span>'}<button class="complete" data-action="complete" data-id="${c.id}" data-focus="complete-${c.id}" aria-pressed="${done}" aria-label="${done?'Desmarcar conclusão de':'Marcar como concluída:'} ${esc(c.name)}">${done?'✓ Concluída':'Concluída?'}</button></div><details class="course-note"><summary>Informações</summary><p>${esc(c.id)}. Pré-requisitos: ${c.prerequisites===null?'não informados':c.prerequisites.length?c.prerequisites.map(id=>esc(courses.find(x=>x.id===id)?.name||id)).join(', '):'nenhum'}.</p>${c.note?`<p>${esc(c.note)}</p>`:''}</details></article>`;}).join('')}</details>`;}).join('');if(focus){document.querySelector(`[data-focus="${focus}"]`)?.focus({preventScroll:true});}}
function render(){const ms=core.meetings(courses,state),pairs=core.conflicts(ms),t=core.totals(courses,state);$('count').textContent=t.count;$('weekly').textContent=fmt(t.minutes);$('hours').textContent=t.selected.unknown?(t.selected.known?t.selected.known+'h + ?':'—'):t.selected.known+'h';$('hours-note').textContent=t.selected.unknown?`CH não informada em ${t.selected.unknown} matéria(s)`:'carga curricular total';$('completed').textContent=t.completed.unknown?(t.completed.known?t.completed.known+'h + ?':'—'):t.completed.known+'h';$('completed-note').textContent=`${t.completedCount} concluída(s)${t.completed.unknown?' · CH pendente':''}`;
const groups=new Map;for(const p of pairs){const ids=[p.a.course.id,p.b.course.id].sort();const key=ids.join('|');if(!groups.has(key))groups.set(key,{names:[p.a.course.name,p.b.course.name],potential:p.potential,days:new Set});const g=groups.get(key);g.days.add(days[p.a.day]);g.potential=g.potential&&p.potential;}
const reqs=core.requirements(courses,state);const missing=reqs.filter(r=>r.missing.length);const unknown=reqs.filter(r=>r.unknown).length;const notes=courses.filter(c=>state.selected[c.id]&&c.note);
$('alerts').innerHTML=(groups.size?`<details class="alert" open><summary>${groups.size} ${groups.size===1?'par de matérias com sobreposição':'pares de matérias com sobreposição'}</summary><ul>${[...groups.values()].map(g=>`<li>${esc(g.names.join(' + '))} · ${[...g.days].join(', ')}${g.potential?' (potencial; aula quinzenal)':''}</li>`).join('')}</ul></details>`:'')+(missing.length?`<div class="alert"><strong>Pré-requisitos pendentes</strong><ul>${missing.map(r=>`<li>${esc(r.course.name)}: concluir ${r.missing.map(id=>esc(courses.find(c=>c.id===id)?.name||id)).join(', ')}.</li>`).join('')}</ul></div>`:'')+(unknown?`<div class="alert info">Pré-requisitos não informados para ${unknown} matéria(s) selecionada(s). Ainda não é possível verificar a elegibilidade.</div>`:'')+(notes.length?`<details class="alert info"><summary>Observações de ${notes.length} matéria(s) selecionada(s)</summary><ul>${notes.map(c=>`<li><b>${esc(c.short)}:</b> ${esc(c.note)}</li>`).join('')}</ul></details>`:'');
$('empty-message').hidden=t.count>0;let html=`<caption class="sr-only">Grade semanal de segunda a sábado</caption><thead><tr><th scope="col">Horário</th>${days.map(d=>`<th scope="col">${d.slice(0,3)}</th>`).join('')}</tr></thead><tbody>`;
for(const [start,end] of slots){if(start==='13:10'||start==='19:00')html+=`<tr class="break"><th scope="row">${start==='13:10'?'12:20–13:10':'18:30–19:00'}</th><td colspan="6">${start==='13:10'?'Almoço':'Jantar'}</td></tr>`;html+=`<tr><th scope="row">${start}–${end}</th>${days.map((d,day)=>{const cell=ms.filter(m=>m.day===day&&core.minute(m.start)<core.minute(end)&&core.minute(start)<core.minute(m.end));const conflict=cell.some(a=>cell.some(b=>a.course.id!==b.course.id&&core.overlap(a,b)));return `<td class="${conflict?'conflict':''}">${cell.map(m=>`<span class="class-block tint-${courses.indexOf(m.course)%4}" title="${esc(m.course.name)} · ${m.start}–${m.end}${m.frequency===2?' · Quinzenal':''}"><b>${conflict?'! ':''}${esc(m.course.short)}${m.frequency===2?' · Q':''}</b><span>Turma ${esc(m.section)}</span></span>`).join('')}</td>`;}).join('')}</tr>`;}
$('schedule').innerHTML=html+'</tbody>';updateSave();}
function change(action,id,value){const c=courses.find(c=>c.id===id);if(!c)throw Error('Disciplina desconhecida');if(action==='complete'){if(state.completed.includes(id))state.completed=state.completed.filter(x=>x!==id);else{state.completed.push(id);delete state.selected[id];}}else if(action==='select'){if(value){if(!c.offered||state.completed.includes(id))throw Error('Disciplina indisponível');state.selected[id]=c.sections[0]?.id||'none';}else delete state.selected[id];}else if(action==='section'){if(!c.sections.some(s=>s.id===value)||state.completed.includes(id)||!c.offered)throw Error('Turma indisponível');state.selected[id]=value;}else throw Error('Ação desconhecida');persist();catalog();render();}
$('courses').addEventListener('change',e=>{if(e.target.dataset.action)change(e.target.dataset.action,e.target.dataset.id,e.target.type==='checkbox'?e.target.checked:e.target.value);});$('courses').addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(b)change(b.dataset.action,b.dataset.id);});
catalog();render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_bioschedule',description:'Lê as disciplinas selecionadas, concluídas e totais da grade atual.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:input=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Esperado um objeto vazio');return {selected:{...state.selected},completed:[...state.completed],totals:core.totals(courses,state)};}})).catch(()=>{});}catch{}}
