const {test}=require('node:test');
const assert=require('node:assert/strict');
const {courses}=require('../data.js');
const core=require('../core.js');
const empty=()=>({selected:{},completed:[]});
test('65 entradas únicas, horários válidos e sem aulas repetidas por turma',()=>{assert.equal(courses.length,65);assert.equal(new Set(courses.map(c=>c.id)).size,65);for(const c of courses){assert.equal(new Set(c.sections.map(s=>s.id)).size,c.sections.length);for(const s of c.sections){assert.equal(new Set(s.meetings.map(m=>`${m.day}:${m.start}:${m.end}`)).size,s.meetings.length);for(const m of s.meetings){assert.ok(m.day>=0&&m.day<=5);assert.ok(core.duration(m)>0);}}}});
test('conflito real entre PSC A1 e MTR B4 desaparece ao trocar para A2',()=>{const state=empty();state.selected={FEELT31107:'A1',FEELT31204:'B4'};assert.equal(core.conflicts(core.meetings(courses,state)).length,4);state.selected.FEELT31204='A2';assert.equal(core.conflicts(core.meetings(courses,state)).length,0);});
test('intervalos apenas adjacentes não conflitam; sobreposição parcial conflita',()=>{assert.equal(core.overlap({day:0,start:'08:00',end:'08:50'},{day:0,start:'08:50',end:'09:40'}),false);assert.equal(core.overlap({day:0,start:'08:00',end:'08:50'},{day:0,start:'08:40',end:'09:30'}),true);});
test('carga semanal desconta intervalos e pondera quinzenais',()=>{let state=empty();state.selected={FAMAT31011:'2'};assert.equal(core.totals(courses,state).minutes,300);state.selected={IBTEC39301:'B1'};assert.equal(core.totals(courses,state).minutes,200);});
test('quinzenas conhecidas alternadas não conflitam',()=>{const a={day:4,start:'08:50',end:'09:40',frequency:2,firstDate:'2026-09-04'};assert.equal(core.overlap(a,{...a,firstDate:'2026-09-11'}),false);assert.equal(core.overlap(a,{...a,firstDate:'2026-09-18'}),true);});
test('cargas desconhecidas não são confundidas com zero ou horas semanais',()=>{const state=empty();state.selected={MO:'Única'};state.completed=['MO'];const t=core.totals(courses,state);assert.deepEqual(t.selected,{known:0,unknown:1});assert.deepEqual(t.completed,{known:0,unknown:1});assert.equal(t.count,1);assert.equal(t.minutes,100);});
test('pré-requisitos exigem conclusão, não mera seleção; dados nulos são desconhecidos',()=>{const fixture=[{id:'A',prerequisites:[]},{id:'B',prerequisites:['A']},{id:'C',prerequisites:null}];const state={selected:{A:'1',B:'1',C:'1'},completed:[]};assert.deepEqual(core.requirements(fixture,state)[1].missing,['A']);state.completed=['A'];assert.deepEqual(core.requirements(fixture,state)[1].missing,[]);assert.equal(core.requirements(fixture,state)[2].unknown,true);});
test('persistência descarta IDs/turmas inválidos e impede concluídas ou não ofertadas na grade',()=>{const s=core.normalize({selected:{FAMAT31011:'2',FEELT31107:'errada',FEELT32703:'none',FEELT32102:'none',invalida:'1'},completed:['FAMAT31011','invalida']},courses);assert.deepEqual(s,{selected:{FEELT32102:'none'},completed:['FAMAT31011']});assert.deepEqual(core.normalize(null,courses),empty());});

test('fluxograma associa as 64 cargas sem atribuir carga à monitoria',()=>{assert.equal(courses.filter(c=>c.hours!==null).length,64);assert.equal(courses.find(c=>c.short==='C1').hours,90);assert.equal(courses.find(c=>c.short==='E-CE1').hours,15);assert.equal(courses.find(c=>c.short==='SEMB1').hours,105);assert.equal(courses.find(c=>c.short==='MO').hours,null);assert.equal(courses.find(c=>c.short==='TCC').period,9);assert.equal(courses.find(c=>c.short==='ESTÁGIO').period,10);});
test('cargas curriculares somam separadamente das aulas semanais',()=>{const state={selected:{FAMAT31011:'2',FEELT31107:'A1'},completed:['FEELT32102']};const t=core.totals(courses,state);assert.deepEqual(t.selected,{known:150,unknown:0});assert.deepEqual(t.completed,{known:90,unknown:0});assert.equal(t.minutes,500);});
test('Física e laboratório aceitam co-requisito simultâneo ou concluído',()=>{const state={selected:{INFIS39031:'1'},completed:[]};assert.deepEqual(core.requirements(courses,state)[0].missingCorequisites,['INFIS39032']);state.selected.INFIS39032='2';assert.ok(core.requirements(courses,state).every(r=>r.missingCorequisites.length===0));delete state.selected.INFIS39032;state.completed=['INFIS39032'];assert.deepEqual(core.requirements(courses,state)[0].missingCorequisites,[]);});
test('Cálculo II requer Cálculo I concluído, não selecionado',()=>{const state={selected:{FAMAT31011:'2',FAMAT31012:'1'},completed:[]};assert.deepEqual(core.requirements(courses,state).find(r=>r.course.short==='C2').missing,['FAMAT31011']);state.completed=['FAMAT31011'];assert.deepEqual(core.requirements(courses,state).find(r=>r.course.short==='C2').missing,[]);});
test('TCC exige 2700h e estágio exige 2300h concluídas',()=>{const state={selected:{FEELT31908:'none',FEELT31005:'none'},completed:['FAMAT31011']};const reqs=core.requirements(courses,state);assert.equal(reqs.find(r=>r.course.short==='TCC').hoursShortfall,2610);assert.equal(reqs.find(r=>r.course.short==='ESTÁGIO').hoursShortfall,2210);const fixture=[{id:'done',hours:2700},{id:'tcc',minCompletedHours:2700,prerequisites:[]}];assert.equal(core.requirements(fixture,{selected:{tcc:'none'},completed:['done']})[0].hoursShortfall,0);});
